# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore '.\RSA console app\RSA console app\RSA console app.csproj'
    - name: Build
      run: dotnet build --no-restore '.\RSA console app\RSA console app\RSA console app.csproj'
    - name: Build test
      run: dotnet build --no-restore '.\RSA console app\RSA console app TEST\RSA console app TEST.csproj'
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover '.\RSA console app\RSA console app TEST\RSA console app TEST.csproj'
    - name: Coverage report to Codecov
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -R '/home/runner/work/RSA/RSA/RSA console app/RSA console app TEST/' -f coverage.opencover.xml
